SimpleShopApiBundle\Entity\Basket:
    type: entity
    table: basket
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        basketProducts:
            type: string
            nullable: false
            length: 2000
            options:
                fixed: false
            column: basket_products
        sessionId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: session_id
        dtCreated:
            type: datetime
            nullable: true
            column: dt_created
        dtUpdated:
            type: datetime
            nullable: true
            column: dt_updated
    lifecycleCallbacks: {  }
